---
- hosts: localhost
  vars:
    home: "{{ lookup('env', 'HOME') }}"
  tasks:
    - name: Install Zinit
      shell: >
          bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)" &&
          source {{ home }}/.zshrc &&
          zinit self-update
      ignore_errors: yes
    
    - name: Install Exa Ubuntu
      when: ansible_distribution == 'Ubuntu'
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400
        pkg:
         - exa

    - name: Install Exa MacOs
      when: ansible_distribution == 'MacOSX'
      become: true
      community.general.homebrew:
        update_homebrew: yes
        pkg:
         - exa


